services:
  aiops-assistant:
    build: .
    container_name: module2-assistant
    ports:
      - "8501:8501"
    volumes:
      - ./incidents.csv:/app/incidents.csv:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
