# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ---------------------------------------------------------------------------
  # VM 1: aiops-control
  # ---------------------------------------------------------------------------
  config.vm.define "aiops-control" do |control|
    control.vm.box = "bento/ubuntu-22.04"
    control.vm.hostname = "aiops-control"
    control.vm.boot_timeout = 600

    # Private network
    control.vm.network "private_network", ip: "192.168.56.10"

    # Port forwarding
    control.vm.network "forwarded_port", guest: 8501, host: 8501, auto_correct: true
    control.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
    control.vm.network "forwarded_port", guest: 9100, host: 9100, auto_correct: true

    control.vm.synced_folder ".", "/vagrant", disabled: true

    control.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "aiops-control"
      vb.gui = true                    # SEE VM screen
      # Network fixes
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      # USB fix
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end

  # ---------------------------------------------------------------------------
  # VM 2: app-server
  # ---------------------------------------------------------------------------
  config.vm.define "app-server" do |app|
    app.vm.box = "bento/ubuntu-22.04"
    app.vm.hostname = "app-server"
    app.vm.boot_timeout = 600

    app.vm.network "private_network", ip: "192.168.56.11"

    app.vm.network "forwarded_port", guest: 80,   host: 8081, auto_correct: true
    app.vm.network "forwarded_port", guest: 9100, host: 9101, auto_correct: true

    app.vm.synced_folder ".", "/vagrant", disabled: true

    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "app-server"
      vb.gui = true                    # SEE VM screen
      # Network fixes
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      # USB fix
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end

end
